version: '3.8'
services:
  frontend:
    image: syntaxname/learning-mono-frontend:latest
    ports:
      - "80:80"

  # migrations: 
  #   image: migrations
  #   build:
  #     args:
  #       - NODE_ENV=production
  #     context: ./packages/backend
  #     dockerfile: ./Dockerfile.migrations
  #   environment:
  #     - DATABASE_URL=postgres://user:pass@db:5432/prod?schema=learning
    

  backend:
    image: syntaxname/learning-mono-backend:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_URL=${CLIENT_URL}
    ports:
      - '3030:3030'
    links: 
      - 'db'

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d prod" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
    volumes:
      - './.data/db:/var/lib/postgresql/data'