version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  frontend:
    image: syntaxname/learning-mono-frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"

  migrations: 
    image: syntaxname/learning-mono-migrations:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
    
  backend:
    image: syntaxname/learning-mono-backend:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_URL=${CLIENT_URL}
    ports:
      - '3030:3030'
    links: 
      - 'db'

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d prod" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
    volumes:
      - './.data/db:/var/lib/postgresql/data'